name: PROD Deployment

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths:
      - 'Web/infra/terraform/**'
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - 'Web/infra/terraform/**'

jobs:
  deploy-prod:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.base.ref, 'main') && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
      - name: Init & Apply PROD
        working-directory: Web/infra/terraform/envs/prod
        run: |
          terraform init -backend-config=backend.tf
          terraform plan -var-file=terraform.tfvars
          terraform apply -auto-approve -var-file=terraform.tfvars
